"""
Seed database with university data for MBA programs
Based on realistic US university data
"""

from database import SessionLocal, University, init_db


def seed_universities():
    """Seed database with 70+ universities"""

    universities_data = [
        # Top Tier / Reach Schools
        {
            "name": "Harvard University",
            "avg_gmat": 730,
            "avg_gpa": 3.7,
            "acceptance_rate": 11.5,
            "ranking": 1,
            "location": "Boston, MA",
            "tuition_cost": 73440,
            "avg_work_experience": 4.7,
        },
        {
            "name": "Stanford University",
            "avg_gmat": 738,
            "avg_gpa": 3.75,
            "acceptance_rate": 6.1,
            "ranking": 2,
            "location": "Stanford, CA",
            "tuition_cost": 74706,
            "avg_work_experience": 4.5,
        },
        {
            "name": "University of Pennsylvania",
            "avg_gmat": 728,
            "avg_gpa": 3.6,
            "acceptance_rate": 19.2,
            "ranking": 3,
            "location": "Philadelphia, PA",
            "tuition_cost": 74500,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Massachusetts Institute of Technology",
            "avg_gmat": 730,
            "avg_gpa": 3.65,
            "acceptance_rate": 14.6,
            "ranking": 4,
            "location": "Cambridge, MA",
            "tuition_cost": 77168,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Northwestern University",
            "avg_gmat": 729,
            "avg_gpa": 3.6,
            "acceptance_rate": 20.2,
            "ranking": 5,
            "location": "Evanston, IL",
            "tuition_cost": 73404,
            "avg_work_experience": 5.1,
        },
        {
            "name": "University of Chicago",
            "avg_gmat": 730,
            "avg_gpa": 3.6,
            "acceptance_rate": 23.6,
            "ranking": 6,
            "location": "Chicago, IL",
            "tuition_cost": 72000,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Columbia University",
            "avg_gmat": 727,
            "avg_gpa": 3.5,
            "acceptance_rate": 16.4,
            "ranking": 7,
            "location": "New York, NY",
            "tuition_cost": 77376,
            "avg_work_experience": 5.1,
        },
        {
            "name": "University of California--Berkeley",
            "avg_gmat": 725,
            "avg_gpa": 3.61,
            "acceptance_rate": 14.8,
            "ranking": 8,
            "location": "Berkeley, CA",
            "tuition_cost": 66202,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Dartmouth College",
            "avg_gmat": 722,
            "avg_gpa": 3.53,
            "acceptance_rate": 22.9,
            "ranking": 9,
            "location": "Hanover, NH",
            "tuition_cost": 74520,
            "avg_work_experience": 4.8,
        },
        {
            "name": "Yale University",
            "avg_gmat": 724,
            "avg_gpa": 3.65,
            "acceptance_rate": 23.7,
            "ranking": 10,
            "location": "New Haven, CT",
            "tuition_cost": 72350,
            "avg_work_experience": 5.0,
        },
        # High Tier
        {
            "name": "New York University",
            "avg_gmat": 720,
            "avg_gpa": 3.5,
            "acceptance_rate": 26.1,
            "ranking": 11,
            "location": "New York, NY",
            "tuition_cost": 74184,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Duke University",
            "avg_gmat": 710,
            "avg_gpa": 3.44,
            "acceptance_rate": 22.7,
            "ranking": 12,
            "location": "Durham, NC",
            "tuition_cost": 70000,
            "avg_work_experience": 4.9,
        },
        {
            "name": "University of Michigan--Ann Arbor",
            "avg_gmat": 716,
            "avg_gpa": 3.4,
            "acceptance_rate": 23.2,
            "ranking": 13,
            "location": "Ann Arbor, MI",
            "tuition_cost": 67300,
            "avg_work_experience": 5.1,
        },
        {
            "name": "Cornell University",
            "avg_gmat": 700,
            "avg_gpa": 3.36,
            "acceptance_rate": 29.6,
            "ranking": 14,
            "location": "Ithaca, NY",
            "tuition_cost": 69440,
            "avg_work_experience": 5.3,
        },
        {
            "name": "University of Virginia",
            "avg_gmat": 706,
            "avg_gpa": 3.41,
            "acceptance_rate": 26.2,
            "ranking": 15,
            "location": "Charlottesville, VA",
            "tuition_cost": 64890,
            "avg_work_experience": 4.7,
        },
        {
            "name": "Carnegie Mellon University",
            "avg_gmat": 691,
            "avg_gpa": 3.35,
            "acceptance_rate": 28.1,
            "ranking": 16,
            "location": "Pittsburgh, PA",
            "tuition_cost": 68000,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of California--Los Angeles",
            "avg_gmat": 714,
            "avg_gpa": 3.5,
            "acceptance_rate": 25.3,
            "ranking": 17,
            "location": "Los Angeles, CA",
            "tuition_cost": 64761,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Texas--Austin",
            "avg_gmat": 690,
            "avg_gpa": 3.42,
            "acceptance_rate": 31.4,
            "ranking": 18,
            "location": "Austin, TX",
            "tuition_cost": 52194,
            "avg_work_experience": 4.8,
        },
        {
            "name": "Emory University",
            "avg_gmat": 680,
            "avg_gpa": 3.3,
            "acceptance_rate": 32.6,
            "ranking": 19,
            "location": "Atlanta, GA",
            "tuition_cost": 63500,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of North Carolina--Chapel Hill",
            "avg_gmat": 701,
            "avg_gpa": 3.43,
            "acceptance_rate": 36.7,
            "ranking": 20,
            "location": "Chapel Hill, NC",
            "tuition_cost": 46015,
            "avg_work_experience": 4.9,
        },
        # Mid-High Tier
        {
            "name": "University of Southern California",
            "avg_gmat": 692,
            "avg_gpa": 3.3,
            "acceptance_rate": 33.0,
            "ranking": 21,
            "location": "Los Angeles, CA",
            "tuition_cost": 64524,
            "avg_work_experience": 5.1,
        },
        {
            "name": "Washington University in St. Louis",
            "avg_gmat": 696,
            "avg_gpa": 3.4,
            "acceptance_rate": 30.5,
            "ranking": 22,
            "location": "St. Louis, MO",
            "tuition_cost": 61750,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Rice University",
            "avg_gmat": 704,
            "avg_gpa": 3.48,
            "acceptance_rate": 25.9,
            "ranking": 23,
            "location": "Houston, TX",
            "tuition_cost": 63628,
            "avg_work_experience": 5.2,
        },
        {
            "name": "Georgetown University",
            "avg_gmat": 692,
            "avg_gpa": 3.32,
            "acceptance_rate": 46.9,
            "ranking": 24,
            "location": "Washington, DC",
            "tuition_cost": 62010,
            "avg_work_experience": 4.8,
        },
        {
            "name": "Vanderbilt University",
            "avg_gmat": 686,
            "avg_gpa": 3.35,
            "acceptance_rate": 32.7,
            "ranking": 25,
            "location": "Nashville, TN",
            "tuition_cost": 58300,
            "avg_work_experience": 4.9,
        },
        {
            "name": "Indiana University",
            "avg_gmat": 670,
            "avg_gpa": 3.32,
            "acceptance_rate": 30.1,
            "ranking": 26,
            "location": "Bloomington, IN",
            "tuition_cost": 29234,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Georgia Institute of Technology",
            "avg_gmat": 683,
            "avg_gpa": 3.31,
            "acceptance_rate": 38.0,
            "ranking": 27,
            "location": "Atlanta, GA",
            "tuition_cost": 40180,
            "avg_work_experience": 5.5,
        },
        {
            "name": "University of Washington",
            "avg_gmat": 691,
            "avg_gpa": 3.44,
            "acceptance_rate": 27.9,
            "ranking": 28,
            "location": "Seattle, WA",
            "tuition_cost": 51495,
            "avg_work_experience": 5.3,
        },
        {
            "name": "Ohio State University",
            "avg_gmat": 673,
            "avg_gpa": 3.37,
            "acceptance_rate": 31.8,
            "ranking": 29,
            "location": "Columbus, OH",
            "tuition_cost": 34592,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Minnesota--Twin Cities",
            "avg_gmat": 683,
            "avg_gpa": 3.36,
            "acceptance_rate": 44.3,
            "ranking": 30,
            "location": "Minneapolis, MN",
            "tuition_cost": 54402,
            "avg_work_experience": 5.1,
        },
        # Mid Tier
        {
            "name": "University of Wisconsin--Madison",
            "avg_gmat": 691,
            "avg_gpa": 3.35,
            "acceptance_rate": 29.6,
            "ranking": 31,
            "location": "Madison, WI",
            "tuition_cost": 49584,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Arizona State University",
            "avg_gmat": 672,
            "avg_gpa": 3.45,
            "acceptance_rate": 34.9,
            "ranking": 32,
            "location": "Tempe, AZ",
            "tuition_cost": 47096,
            "avg_work_experience": 5.2,
        },
        {
            "name": "Pennsylvania State University--University Park",
            "avg_gmat": 648,
            "avg_gpa": 3.28,
            "acceptance_rate": 29.7,
            "ranking": 33,
            "location": "University Park, PA",
            "tuition_cost": 27690,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Florida",
            "avg_gmat": 683,
            "avg_gpa": 3.36,
            "acceptance_rate": 43.5,
            "ranking": 34,
            "location": "Gainesville, FL",
            "tuition_cost": 12737,
            "avg_work_experience": 5.5,
        },
        {
            "name": "University of Maryland--College Park",
            "avg_gmat": 670,
            "avg_gpa": 3.29,
            "acceptance_rate": 37.8,
            "ranking": 35,
            "location": "College Park, MD",
            "tuition_cost": 57678,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Texas A&M University--College Station",
            "avg_gmat": 661,
            "avg_gpa": 3.38,
            "acceptance_rate": 35.5,
            "ranking": 36,
            "location": "College Station, TX",
            "tuition_cost": 28998,
            "avg_work_experience": 5.3,
        },
        {
            "name": "University of Georgia",
            "avg_gmat": 665,
            "avg_gpa": 3.31,
            "acceptance_rate": 41.2,
            "ranking": 37,
            "location": "Athens, GA",
            "tuition_cost": 14064,
            "avg_work_experience": 4.8,
        },
        {
            "name": "Brigham Young University",
            "avg_gmat": 670,
            "avg_gpa": 3.56,
            "acceptance_rate": 48.9,
            "ranking": 38,
            "location": "Provo, UT",
            "tuition_cost": 13360,
            "avg_work_experience": 5.7,
        },
        {
            "name": "University of Notre Dame",
            "avg_gmat": 691,
            "avg_gpa": 3.33,
            "acceptance_rate": 35.0,
            "ranking": 39,
            "location": "Notre Dame, IN",
            "tuition_cost": 56280,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Boston University",
            "avg_gmat": 676,
            "avg_gpa": 3.39,
            "acceptance_rate": 41.7,
            "ranking": 40,
            "location": "Boston, MA",
            "tuition_cost": 58560,
            "avg_work_experience": 4.8,
        },
        # Accessible Tier
        {
            "name": "Michigan State University",
            "avg_gmat": 667,
            "avg_gpa": 3.36,
            "acceptance_rate": 38.2,
            "ranking": 41,
            "location": "East Lansing, MI",
            "tuition_cost": 49984,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of California--Irvine",
            "avg_gmat": 670,
            "avg_gpa": 3.32,
            "acceptance_rate": 36.8,
            "ranking": 42,
            "location": "Irvine, CA",
            "tuition_cost": 56393,
            "avg_work_experience": 5.2,
        },
        {
            "name": "University of California - Davis",
            "avg_gmat": 671,
            "avg_gpa": 3.37,
            "acceptance_rate": 40.1,
            "ranking": 43,
            "location": "Davis, CA",
            "tuition_cost": 60572,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Tennessee",
            "avg_gmat": 648,
            "avg_gpa": 3.34,
            "acceptance_rate": 41.9,
            "ranking": 44,
            "location": "Knoxville, TN",
            "tuition_cost": 31160,
            "avg_work_experience": 5.1,
        },
        {
            "name": "Iowa State University",
            "avg_gmat": 645,
            "avg_gpa": 3.32,
            "acceptance_rate": 52.7,
            "ranking": 45,
            "location": "Ames, IA",
            "tuition_cost": 24508,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Alabama",
            "avg_gmat": 651,
            "avg_gpa": 3.42,
            "acceptance_rate": 47.8,
            "ranking": 46,
            "location": "Tuscaloosa, AL",
            "tuition_cost": 30250,
            "avg_work_experience": 5.3,
        },
        {
            "name": "Boston College",
            "avg_gmat": 676,
            "avg_gpa": 3.36,
            "acceptance_rate": 39.2,
            "ranking": 47,
            "location": "Chestnut Hill, MA",
            "tuition_cost": 56780,
            "avg_work_experience": 4.9,
        },
        {
            "name": "University of Rochester",
            "avg_gmat": 663,
            "avg_gpa": 3.35,
            "acceptance_rate": 35.4,
            "ranking": 48,
            "location": "Rochester, NY",
            "tuition_cost": 52974,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Babson College",
            "avg_gmat": 643,
            "avg_gpa": 3.22,
            "acceptance_rate": 34.6,
            "ranking": 49,
            "location": "Wellesley, MA",
            "tuition_cost": 54096,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of South Carolina",
            "avg_gmat": 662,
            "avg_gpa": 3.35,
            "acceptance_rate": 48.7,
            "ranking": 50,
            "location": "Columbia, SC",
            "tuition_cost": 51298,
            "avg_work_experience": 5.2,
        },
        # Target/Safety Schools
        {
            "name": "University of Arizona",
            "avg_gmat": 652,
            "avg_gpa": 3.38,
            "acceptance_rate": 43.2,
            "ranking": 51,
            "location": "Tucson, AZ",
            "tuition_cost": 29362,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Rutgers University--Newark and New Brunswick",
            "avg_gmat": 654,
            "avg_gpa": 3.40,
            "acceptance_rate": 44.6,
            "ranking": 52,
            "location": "Newark, NJ",
            "tuition_cost": 32136,
            "avg_work_experience": 5.1,
        },
        {
            "name": "Syracuse University",
            "avg_gmat": 640,
            "avg_gpa": 3.29,
            "acceptance_rate": 42.3,
            "ranking": 53,
            "location": "Syracuse, NY",
            "tuition_cost": 49734,
            "avg_work_experience": 4.8,
        },
        {
            "name": "University of Miami",
            "avg_gmat": 652,
            "avg_gpa": 3.3,
            "acceptance_rate": 45.8,
            "ranking": 54,
            "location": "Coral Gables, FL",
            "tuition_cost": 52080,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Southern Methodist University",
            "avg_gmat": 664,
            "avg_gpa": 3.35,
            "acceptance_rate": 42.0,
            "ranking": 55,
            "location": "Dallas, TX",
            "tuition_cost": 49350,
            "avg_work_experience": 5.2,
        },
        {
            "name": "Case Western Reserve University",
            "avg_gmat": 652,
            "avg_gpa": 3.31,
            "acceptance_rate": 50.2,
            "ranking": 56,
            "location": "Cleveland, OH",
            "tuition_cost": 48900,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Fordham University",
            "avg_gmat": 643,
            "avg_gpa": 3.30,
            "acceptance_rate": 46.8,
            "ranking": 57,
            "location": "New York, NY",
            "tuition_cost": 56484,
            "avg_work_experience": 4.9,
        },
        {
            "name": "George Washington University",
            "avg_gmat": 657,
            "avg_gpa": 3.33,
            "acceptance_rate": 49.7,
            "ranking": 58,
            "location": "Washington, DC",
            "tuition_cost": 33270,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Denver",
            "avg_gmat": 626,
            "avg_gpa": 3.27,
            "acceptance_rate": 52.1,
            "ranking": 59,
            "location": "Denver, CO",
            "tuition_cost": 52515,
            "avg_work_experience": 5.1,
        },
        {
            "name": "University of Colorado",
            "avg_gmat": 638,
            "avg_gpa": 3.32,
            "acceptance_rate": 56.4,
            "ranking": 60,
            "location": "Boulder, CO",
            "tuition_cost": 38256,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Kentucky",
            "avg_gmat": 631,
            "avg_gpa": 3.35,
            "acceptance_rate": 54.2,
            "ranking": 61,
            "location": "Lexington, KY",
            "tuition_cost": 31386,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Houston",
            "avg_gmat": 630,
            "avg_gpa": 3.27,
            "acceptance_rate": 57.8,
            "ranking": 62,
            "location": "Houston, TX",
            "tuition_cost": 24756,
            "avg_work_experience": 5.3,
        },
        {
            "name": "Baylor University",
            "avg_gmat": 636,
            "avg_gpa": 3.34,
            "acceptance_rate": 50.5,
            "ranking": 63,
            "location": "Waco, TX",
            "tuition_cost": 49164,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Texas Christian University",
            "avg_gmat": 641,
            "avg_gpa": 3.35,
            "acceptance_rate": 48.1,
            "ranking": 64,
            "location": "Fort Worth, TX",
            "tuition_cost": 47910,
            "avg_work_experience": 5.1,
        },
        {
            "name": "University of Arkansas",
            "avg_gmat": 620,
            "avg_gpa": 3.41,
            "acceptance_rate": 61.3,
            "ranking": 65,
            "location": "Fayetteville, AR",
            "tuition_cost": 25676,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Cincinnati",
            "avg_gmat": 618,
            "avg_gpa": 3.30,
            "acceptance_rate": 62.9,
            "ranking": 66,
            "location": "Cincinnati, OH",
            "tuition_cost": 26334,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University of Utah",
            "avg_gmat": 650,
            "avg_gpa": 3.38,
            "acceptance_rate": 45.2,
            "ranking": 67,
            "location": "Salt Lake City, UT",
            "tuition_cost": 58476,
            "avg_work_experience": 5.2,
        },
        {
            "name": "William & Mary",
            "avg_gmat": 667,
            "avg_gpa": 3.32,
            "acceptance_rate": 41.0,
            "ranking": 68,
            "location": "Williamsburg, VA",
            "tuition_cost": 43623,
            "avg_work_experience": 5.0,
        },
        {
            "name": "University at Buffalo",
            "avg_gmat": 609,
            "avg_gpa": 3.25,
            "acceptance_rate": 65.7,
            "ranking": 69,
            "location": "Buffalo, NY",
            "tuition_cost": 25710,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Stevens Institute of Technology",
            "avg_gmat": 645,
            "avg_gpa": 3.28,
            "acceptance_rate": 54.8,
            "ranking": 70,
            "location": "Hoboken, NJ",
            "tuition_cost": 52410,
            "avg_work_experience": 5.0,
        },
        # Additional schools
        {
            "name": "University of South Florida",
            "avg_gmat": 595,
            "avg_gpa": 3.24,
            "acceptance_rate": 68.9,
            "ranking": 71,
            "location": "Tampa, FL",
            "tuition_cost": 21126,
            "avg_work_experience": 4.8,
        },
        {
            "name": "CUNY Bernard M. Baruch College",
            "avg_gmat": 610,
            "avg_gpa": 3.30,
            "acceptance_rate": 66.2,
            "ranking": 72,
            "location": "New York, NY",
            "tuition_cost": 19590,
            "avg_work_experience": 5.0,
        },
        {
            "name": "The University of Texas at Dallas",
            "avg_gmat": 632,
            "avg_gpa": 3.33,
            "acceptance_rate": 60.1,
            "ranking": 73,
            "location": "Dallas, TX",
            "tuition_cost": 15654,
            "avg_work_experience": 5.2,
        },
        {
            "name": "North Carolina A&T State University",
            "avg_gmat": 548,
            "avg_gpa": 3.15,
            "acceptance_rate": 71.3,
            "ranking": 74,
            "location": "Greensboro, NC",
            "tuition_cost": 18621,
            "avg_work_experience": 5.0,
        },
        {
            "name": "Howard University",
            "avg_gmat": 575,
            "avg_gpa": 3.20,
            "acceptance_rate": 69.5,
            "ranking": 75,
            "location": "Washington, DC",
            "tuition_cost": 38626,
            "avg_work_experience": 5.1,
        },
        {
            "name": "Chapman University",
            "avg_gmat": 615,
            "avg_gpa": 3.28,
            "acceptance_rate": 63.4,
            "ranking": 76,
            "location": "Orange, CA",
            "tuition_cost": 53130,
            "avg_work_experience": 4.9,
        },
    ]

    db = SessionLocal()

    try:
        # Check if data already exists
        existing_count = db.query(University).count()
        if existing_count > 0:
            print(
                f"Database already contains {existing_count} universities. Skipping seed."
            )
            return

        # Add all universities
        for uni_data in universities_data:
            university = University(
                name=uni_data["name"],
                program_type="MBA",
                avg_gmat=uni_data["avg_gmat"],
                avg_gpa=uni_data["avg_gpa"],
                acceptance_rate=uni_data["acceptance_rate"],
                location=uni_data.get("location"),
                ranking=uni_data.get("ranking"),
                avg_work_experience=uni_data.get("avg_work_experience", 5.0),
                tuition_cost=uni_data.get("tuition_cost"),
            )
            db.add(university)

        db.commit()
        print(f"Successfully seeded {len(universities_data)} universities!")

    except Exception as e:
        print(f"Error seeding database: {e}")
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    print("Initializing database...")
    init_db()
    print("Seeding universities...")
    seed_universities()
    print("Done!")
